[build]
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Это ключ: мы помечаем пакеты как внешние, чтобы esbuild их игнорировал
  external_node_modules = ["serverless-http", "express"]