[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  # Это принудительно говорит Netlify: "Не ищи эту библиотеку в бандле, 
  # она будет доступна в среде выполнения Node"
  external_node_modules = ["serverless-http"]